-- Credit to xHeptc for Kavo UILib
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Ploobware v1.11", "Serpent")

local function chat(msg)
    game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(msg, "All")
end


local Race = Window:NewTab("Race")
    local GeneralRace = Race:NewSection("General Racial Facts")
        GeneralRace:NewButton("Evolution is accelerating + human races diverging", "https://archive.md/4c4M1", function()
            chat("Human evolution is not merely ongoing but is in fact accelerating. In addition, human races are diverging into separate species, not mixing into one.")
            setclipboard("archive.md/4c4M1")
        end)
        GeneralRace:NewButton("Immigration reduced average USA skill level", "https://archive.md/JwhM7", function()
            chat("Immigration has reduced the average skill level of Americans.")
            setclipboard("archive.md/JwhM7")
        end)
        GeneralRace:NewButton("Melanin concentration = correlated w/ aggression", "https://archive.md/ps4nT", function()
            chat("Melanin concentration may directly correlate with aggression.")
            setclipboard("archive.md/ps4nT")
        end)
        GeneralRace:NewButton("Race predicts crime better than poverty", "https://archive.md/uCbLq", function()
            chat("Race is a better predictor of crime than poverty.")
            setclipboard("archive.md/uCbLq")
        end)
        GeneralRace:NewButton("Black+Hispanic % is best crime predictor", "https://archive.md/uCbLq", function()
            chat("The percentage of Blacks and Hispanics in an area, not poverty, is the best predictor of crime.")
            setclipboard("archive.md/uCbLq")
        end)
        GeneralRace:NewButton("1/2 of hate crimes are Black vs Hispanic", "https://archive.md/y0Ys9", function()
            chat("Half of hate crimes are Blacks and Hispanics attacking each other.")
            setclipboard("archive.md/y0Ys9")
        end)
        GeneralRace:NewButton("White+Asian women get more successful marriages", "https://archive.md/hFZOk", function()
            chat("White and Asian women have more successful mzxzrriages than Black or Hispanic women.")
            setclipboard("archive.md/hFZOk")
        end)
        GeneralRace:NewButton("High testosterone men are more racist", "https://archive.md/6ra6J", function()
            chat("Men with high txstosterone, who are also more attractive, are more likely to be racist.")
            setclipboard("archive.md/6ra6J")
        end)
        GeneralRace:NewButton("Most students accused of rape are nonwhite", "https://archive.md/t70ER", function()
            chat("Most students accused of seskual assault on college campuses are not White.")
            setclipboard("archive.md/t70ER")
        end)
    local WhiteRace = Race:NewSection("The White Race")
        WhiteRace:NewButton("White men are stronger", "https://archive.md/MvhpI", function()
            chat("Wh ite men are pound-for-pound stronger than Black or Hispanic men.")
            setclipboard("archive.md/MvhpI")
        end)
        WhiteRace:NewButton("Germans/Nords have lowest time preference", "https://archive.md/Olkun", function()
            chat("Germanic/Nordic people have lower time preference than any other group.")
            setclipboard("archive.md/Olkun")
        end)
        WhiteRace:NewButton("Minorities would rather live among Whites", "https://archive.md/tdngJ", function()
            chat("Asians, Hispanics and Blacks would rather live among White people than among other minorities. ")
            setclipboard("archive.md/tdngJ")
        end)
        WhiteRace:NewButton("90% of gang members are nonwhite", "https://archive.md/uCbLq", function()
            chat("90% of gang members are not White.")
            setclipboard("archive.md/uCbLq")
        end)
        WhiteRace:NewButton("Western aesthetic is universally appealing", "https://archive.md/pKE5I", function()
            chat("The Western aesthetic of big eyes and pale skin is universally considered appealing.")
            setclipboard("archive.md/pKE5I")
        end)
        WhiteRace:NewButton("The West has the most significant art figures", "https://archive.md/PnZu4", function()
            chat("There are more significant artistic figures from West than from the rest of the world combined.")
            setclipboard("archive.md/PnZu4")
        end)

    local BlackRace = Race:NewSection("The Black Race")
        BlackRace:NewButton("Africans have undergone less recent evolution", "https://archive.md/zX5p9", function()
            chat("Europeans and Asians are subject to more recent evolution than Africans. ")
            setclipboard("archive.md/zX5p9")
        end)
        BlackRace:NewButton(">100 White women are raped by Blacks daily", "https://archive.md/ZiEwP", function()
            chat("Over 100 Wh ite women are rzxzsped by Bl ack men DAILY in the United States.")
            setclipboard("archive.md/ZiEwP")
        end)
        BlackRace:NewButton("Blacks overrepresented in serial killings", "https://archive.md/UoAI0", function()
            chat("Blacks are overrepresented in serial killings, and this overrepresentation is increasing.")
            setclipboard("archive.md/UoAI0")
        end)
        BlackRace:NewButton("Blacks overrepresented in child abuse", "https://archive.md/G57w1", function()
            chat("Blacks are overrepresented among child abusers, and this isn't due to biased reporting.")
            setclipboard("archive.md/G57w1")
        end)
        BlackRace:NewButton("Average Black IQ is 15 lower than White", "https://archive.md/ql18C", function()
            chat("The average Black has an IQ score 1 standard deviation (15 IQ points) lower than the average White.")
            setclipboard("archive.md/ql18C")
        end)
        BlackRace:NewButton("The Black-White IQ gap remains in South Africa", "https://archive.md/QA9Fd", function()
            chat("The Black-White IQ gap in the US is equal to the gap in S. Africa, even though SA is ruled by Blacks.")
            setclipboard("archive.md/QA9Fd")
        end)
        BlackRace:NewButton("The B-W IQ gap remains in identical environments", "https://archive.md/jSQz8", function()
            chat("The Black-White IQ gap exists even when both races are raised in identical environments.")
            setclipboard("archive.md/jSQz8")
        end)
        BlackRace:NewButton("Blacks commit 50% of murders, 1/3 of rapes", "https://archive.md/QJWNh", function()
            chat("Blacks commit 50% of all murders and 1/3 of all raezxpes despite being only 12% of the population!")
            setclipboard("archive.md/QJWNh")
        end)
        BlackRace:NewButton("73% of Black babies are bastards", "https://archive.md/3Ocfl", function()
            chat("73% of Black babies are born out of wedlozxck. ")
            setclipboard("archive.md/3Ocfl")
        end)
        BlackRace:NewButton("Black women are 4x more likely to be overweight", "https://archive.md/tdngJ", function()
            chat("Black women are four times more likely to be over weight than White women.")
            setclipboard("archive.md/tdngJ")
        end)
        BlackRace:NewButton("Students perform worse around Black students", "https://archive.md/zP8E9", function()
            chat("Students of all races perform worse in schools with more Black students.")
            setclipboard("archive.md/zP8E9")
        end)
        BlackRace:NewButton("Blacks are 4x more likely to murder their child", "https://archive.md/3aVLN", function()
            chat("Blacks are four times as likely as Whites to murdzxer their infzxnts.")
            setclipboard("archive.md/3aVLN")
        end)
        BlackRace:NewButton("Africans have only one Nobel prize", "https://archive.md/26JQR", function()
            chat("Europeans have been awarded 540 Nobel prizes. Africans have been awarded one.")
            setclipboard("archive.md/26JQR")
        end)
        BlackRace:NewButton("90% of B-W interracial violence is from Blacks", "https://archive.md/ZcXVv", function()
            chat("90% of interracial violence between Blacks and Whites is committed by Blacks. ")
            setclipboard("archive.md/ZcXVv")
        end)
        BlackRace:NewButton("In South Africa, rape is normalized", "https://archive.md/41ye6", function()
            chat("In S. Africa, raezxpe is seen as 'a legitimate activity' and committed out of boredom.")
            setclipboard("archive.md/41ye6")
        end)
        BlackRace:NewButton("1200 ppl (mostly blacks) die for sneakers yearly", "https://archive.md/UcAxp", function()
            chat("1200 people die over sneakers every year. Most of them are Black.")
            setclipboard("archive.md/UcAxp")
        end)
        BlackRace:NewButton("Blacks are 7x more likely to murder", "https://archive.md/uCbLq", function()
            chat("Blacks are seven times more likely than Whites to commit murder.")
            setclipboard("archive.md/uCbLq")
        end)

    local InterracialRelationships = Race:NewSection("Interracial Relationships")
        InterracialRelationships:NewButton("Status is gained by dating Whites", "https://archive.md/tdngJ", function()
            chat("Nozxnwhite daters gain status by being with any White. Whites, on the other hand, have little to gain by doing so with minorities.")
            setclipboard("archive.md/tdngJ")
        end)
        InterracialRelationships:NewButton("W/B babies are less healthy", "https://archive.md/GPTnt", function()
            chat("White+Black mixed babies are less healthy than White babies.")
            setclipboard("archive.md/GPTnt")
        end)
        InterracialRelationships:NewButton("Race mixing results in more stillbirths", "https://archive.md/SKw27", function()
            chat("Mixed race couples are more likely to have stillborn babies than same-race couples.")
            setclipboard("archive.md/SKw27")
        end)
        InterracialRelationships:NewButton("B/W children most likely to make poor decisions", "https://archive.md/P9Ghc", function()
            chat("Black-White children are more likely than both Black and Whites to make poor decisions.")
            setclipboard("archive.md/P9Ghc")
        end)
        InterracialRelationships:NewButton("90% of mudsharks never marry", "https://archive.md/hLoZr", function()
            chat("90% of mothers to a child with a Blzxck man never mzxrry the father.")
            setclipboard("archive.md/hLoZr")
        end)
        InterracialRelationships:NewButton("98% of mudsharks are not supported by Black fathers", "https://archive.md/hLoZr", function()
            chat("98% of White mothers to a child with Black men are not financially supported by the father.")
            setclipboard("archive.md/hLoZr")
        end)
        InterracialRelationships:NewButton("Race-mixers give less parental support", "https://archive.md/M7itt", function()
            chat("Razxce-mixcrs may give less parental support to their children because of greater genetic distance.")
            setclipboard("archive.md/M7itt")
        end)
        InterracialRelationships:NewButton("W/B couples have more violence than White couples", "https://archive.md/JSsoP", function()
            chat("White-Black couples have more partner violence than White couples and as much violence as Black couples.")
            setclipboard("archive.md/JSsoP")
        end)
        InterracialRelationships:NewButton("Interracial marriage have 23% divorce chance", "https://archive.md/1zdiR", function()
            chat("Interracial mzxarriagces have a 23.5% chance of dizvorxce, compared to 13% for same-race couples.")
            setclipboard("archive.md/1zdiR")
        end)
        InterracialRelationships:NewButton("Mixed race kids suffer from social issues", "https://archive.md/dZqP1", function()
            chat("Mixed race kids suffer from low self-esteem, social isolation, and poor family dynamics.")
            setclipboard("archive.md/dZqP1")
        end)
        InterracialRelationships:NewButton("Educated people exclude Blacks as partners", "https://archive.md/t497x", function()
            chat("Better educated men and women are more likely to exclzxde Bla cks as partners.")
            setclipboard("archive.md/t497x")
        end)
        InterracialRelationships:NewButton("97% of mudsharks use welfare", "https://archive.md/hLoZr", function()
            chat("97% of Whi te mothers with Blzxck partners have used welfare.")
            setclipboard("archive.md/hLoZr")
        end)

    local AsianRace = Race:NewSection("The Asian Race")
        AsianRace:NewButton("40% of Asian women won't date Asian men", "https://archive.md/tdngJ", function()
            chat("40% of Asian women refuse to dzxsate Asian men.")
            setclipboard("archive.md/tdngJ")
        end)
        AsianRace:NewButton("Asian women prefer White men", "https://archive.md/tdngJ", function()
            chat("Asian women find Whi te men more attrzxctive than Asian men.")
            setclipboard("archive.md/tdngJ")
        end)
        AsianRace:NewButton("50% of young Korean women have plastic surgery", "https://archive.md/pKE5I", function()
            chat("Half of young Korean women have had plastic surgery.")
            setclipboard("archive.md/pKE5I")
        end)
        AsianRace:NewButton("Asians are more conformative", "https://archive.md/XKBGV", function()
            chat("Evidence indicates Asians have genetically less individuality and more conformity than White people.")
            setclipboard("archive.md/XKBGV")
        end)
        AsianRace:NewButton("Asians 9x more likely to join gangs", "https://archive.md/uCbLq", function()
            chat("Asians are nine times more likely than Whites to be members of gangs.")
            setclipboard("archive.md/uCbLq")
        end)

    local HispanicRace = Race:NewSection("The Hispanic Race")
        HispanicRace:NewButton("64% of Hispanics have IQ too low for army", "https://archive.md/tgXNc", function()
            chat("64% of Hispanics have IQ scores too low to enter the military.")
            setclipboard("archive.md/tgXNc")
        end)
        HispanicRace:NewButton("48% of Hispanics are bastards", "https://archive.md/5pRsY", function()
            chat("48% of Hispanics are born out of wzxdlzck, double the rate of illegitimate White births.")
            setclipboard("archive.md/5pRsY")
        end)
        HispanicRace:NewButton("Noncitizen Hispanics are 29% of prison pop.", "https://archive.md/et1W1", function()
            chat("Non-citizen Hispanics are 29% of the federal prison population, despite only being 5% of the population.")
            setclipboard("archive.md/et1W1")
        end)
        HispanicRace:NewButton("Hispanic immigration raised Black crime", "https://archive.md/j86sp", function()
            chat("Hispanic immigration has displaced African Americans and raised the Black crime rate.")
            setclipboard("archive.md/j86sp")
        end)
        HispanicRace:NewButton("Hispanics get low college degrees", "https://archive.md/pGuHP", function()
            chat("The share of college degrees earned by Hispanics, already very low, has not changed in two decades.")
            setclipboard("archive.md/pGuHP")
        end)
        HispanicRace:NewButton("Hispanics have a 50% dropout rate", "https://archive.md/pGuHP", function()
            chat("The Hispanic high school drop out rate of 50% is unchanged across generations.")
            setclipboard("archive.md/pGuHP")
        end)
        HispanicRace:NewButton("Hispanic children have higher crime rates", "https://archive.md/5pRsY", function()
            chat("The children of Hisp anic 'im mi grants' have a higher crime rate than the 'im mi grants' themselves.")
            setclipboard("archive.md/5pRsY")
        end)

    local RaceValidity = Race:NewSection("Validity of Race")
        RaceValidity:NewButton("Race can be determined via brain scan", "https://archive.md/D9RFT", function()
            chat("Race can be determined via brain scans.")
            setclipboard("archive.md/D9RFT")
        end)
        RaceValidity:NewButton("97% of whites have no black lineage", "https://archive.md/qOuZp", function()
            chat("97% of Whites have no Black ancestry whatsoever.")
            setclipboard("archive.md/qOuZp")
        end)
        RaceValidity:NewButton("Races are subspecies", "https://archive.md/1VeLF", function()
            chat("Races are human subspecies.")
            setclipboard("archive.md/1VeLF")
        end)
        RaceValidity:NewButton("Race can be determined via genetics", "https://archive.md/llqn5", function()
            chat("Race can be determined via genetics with certainty for >99.8% of individuals.")
            setclipboard("archive.md/llqn5")
        end)
        RaceValidity:NewButton("Racial categories have biological meaning", "https://archive.md/QaFUS", function()
            chat("Common-sense racial categories have biological meaning.")
            setclipboard("archive.md/QaFUS")
        end)


local LGBT = Window:NewTab("LGBT and Gender")
    local Homosexuality = LGBT:NewSection("Gays")
        Homosexuality:NewButton("99.8% of LGB teens change within 13 yrs", "https://archive.md/WYd97", function()
            chat("99.8% of lesbian, gay and bi teens will change their orientation within 13 years.")
            setclipboard("archive.md/WYd97")
        end)
        Homosexuality:NewButton("2/3 gays change to straight after 5 yrs", "https://archive.md/iRN76", function()
            chat("Two-thirds of men and women who were gay change their orientation to straight five years later.")
            setclipboard("archive.md/iRN76")
        end)
        Homosexuality:NewButton("24-90% of lesbians psychologically abused", "https://archive.md/G52zK", function()
            chat("Between 24% and 90% of lesbians report being psychologically abused by their partners.")
            setclipboard("archive.md/G52zK")
        end)
        Homosexuality:NewButton("Children of gays are more likely to be gay", "https://archive.md/KZTop", function()
            chat("The children of gays are several times more likely to be gay themselves.")
            setclipboard("archive.md/KZTop")
        end)
        Homosexuality:NewButton("Gays have more depressive disorders", "https://archive.md/f8nZ3", function()
            chat("Gzxys are more likely than straight people to have anxiety, depression, bipolar disorder, and to commit svxccide.")
            setclipboard("archive.md/f8nZ3")
        end)
        Homosexuality:NewButton("Gays are more likely to be mentally ill", "https://archive.md/cq5FR", function()
            chat("Gzxys are more likely than straight people to have mental illness.")
            setclipboard("archive.md/cq5FR")
        end)
        Homosexuality:NewButton("Gays are 6x more likely to commit suicide", "https://archive.md/W1q4T", function()
            chat("Gzxy men are six times more likely to commit svxccide than straight men.")
            setclipboard("archive.md/W1q4T")
        end)
        Homosexuality:NewButton("Most gays say >50% of partners are strangers", "https://archive.md/W1q4T", function()
            chat("79% of homosexual men say over half of their saezx partners are strangers.")
            setclipboard("archive.md/W1q4T")
        end)
        Homosexuality:NewButton("43% of gays have >500 partners", "https://archive.md/wQ9d6", function()
            chat("43% of gay men have over 500 partners.")
            setclipboard("archive.md/wQ9d6")
        end)
        Homosexuality:NewButton("Gays are 2x as likely to mix races", "https://archive.md/uiSMX", function()
            chat("Gzxy men are twice as likely as straight men to be in interracial partnerships.")
            setclipboard("archive.md/uiSMX")
        end)
        Homosexuality:NewButton("Gay men are 60x more likely to have HIV", "https://archive.md/Yf1nH", function()
            chat("Gzxy men are 60x more likely to have HZXV than straight men.")
            setclipboard("archive.md/Yf1nH")
        end)
        Homosexuality:NewButton("Gay men are 63% of syphilis cases", "https://archive.md/f8nZ3", function()
            chat("Gzxy men (1.65% of the US population) make up 63% of the country's syphzxlis cases.")
            setclipboard("archive.md/f8nZ3")
        end)
        Homosexuality:NewButton("Gay parents not as capable of raising kids", "https://archive.md/X0js6", function()
            chat("Claims that gay parents are just as capable of raising children as straight parents are misrepresented.")
            setclipboard("archive.md/X0js6")
        end)
        Homosexuality:NewButton("Arguments for homosexuality are fallacies", "https://archive.md/VtXa4", function()
            chat("Liberal arguments in favor of homosexuality are based on logical fallacies.")
            setclipboard("archive.md/VtXa4")
        end)
        Homosexuality:NewButton("40-60% of serial killers are gay", "https://archive.md/f8nZ3", function()
            chat("40% to 60% of serial killers are gay.")
            setclipboard("archive.md/f8nZ3")
        end)
        Homosexuality:NewButton("4.5% of gays are faithful", "https://archive.md/j0Ifk", function()
            chat("4.5% of gay men are faithful, compared to 75% of straight men.")
            setclipboard("archive.md/j0Ifk")
        end)
        Homosexuality:NewButton("Monogamy is not central in gay relationships", "https://archive.md/f8nZ3", function()
            chat("Monogzxmy is not a central feature of most gay partnerships.")
            setclipboard("archive.md/f8nZ3")
        end)
        Homosexuality:NewButton("Lesbians are 2.5x more likely to be obese", "https://archive.md/f8nZ3", function()
            chat("Leszx bizxns are 2.5x more likely than straight women to be obezxse.")
            setclipboard("archive.md/f8nZ3")
        end)
        Homosexuality:NewButton("Married lesbians are 2-3 times more likely to divorce", "https://archive.md/f8nZ3", function()
            chat("Mzxrried lesbians are 2-3 times more likely to divzxzrce than straight couples.")
            setclipboard("archive.md/f8nZ3")
        end)
        Homosexuality:NewButton("America spent $700M on promoting gay rights", "https://archive.md/O7GHh", function()
            chat("America has spent $700 million promoting gay rights abroad - an “integral” part of American foreign policy.")
            setclipboard("archive.md/O7GHh")
        end)

    local Transsexuality = LGBT:NewSection("Transsexuality")
        Transsexuality:NewButton("Trans are 4x more likely to have HIV", "https://archive.md/G8AmS", function()
            chat("Transgenders are four times more likely than the average person to be infzxzted with HZXV.")
            setclipboard("archive.md/G8AmS")
        end)
        Transsexuality:NewButton("Suicide rates increase post-surgery", "https://archive.md/fvdkz", function()
            chat("Suiczxzide rates INCREASE after reassignment surgery.")
                setclipboard("archive.md/fvdkz")
        end)
        Transsexuality:NewButton("MtFs are 18x more likely to violently offend", "https://archive.ph/zWBXC", function()
            chat("A 2011 study found that MtF transitioners are 18x more likely than biological females to be convicted of a violent offence.")
            setclipboard("archive.ph/zWBXC")
        end)
        Transsexuality:NewButton("58.9% of MtF prisoners are rapists", "https://archive.ph/zWBXC", function()
            chat("In 2019, 58.9% of transwomen in UK prisons had committed scx crimes, compared to only 16.8% of cis men.")
            setclipboard("archive.ph/zWBXC")
        end)
        Transsexuality:NewButton("Autism 10x more prevalent in trans kids", "https://archive.ph/vFGPc", function()
            chat("A 2010 study found that autism spectrum disorder is ten times more prevalent among children and adolescents who are referred to gender identitity clinics.")
            setclipboard("archive.ph/vFGPc")
        end)
        Transsexuality:NewButton("23% of trans kids have aspergers", "https://archive.ph/6dLkh", function()
            chat("A 2016 study found that 23% of people with gender dysphoria had Asperger syndrome or autism.")
            setclipboard("archive.ph/6dLkh")
        end)
        Transsexuality:NewButton("Trans adults 3-6x more likely to have autism", "https://archive.ph/fYTb7", function()
            chat("In 2020, Cambridge researchers determined that transgender adults are 3 to 6 times more likely to have an autism diagnosis than cisgender people.")
            setclipboard("archive.ph/fYTb7")
        end)
        Transsexuality:NewButton("88% of dysphoric kids lose their beliefs", "https://archive.md/EpxLV", function()
            chat("About 88% of children who have gender dysphoria do not hold those beliefs when they grow older.")
                setclipboard("archive.md/EpxLV")
        end)
        Transsexuality:NewButton("Only 12% of MtF boys hold the belief later on", "https://archive.md/S3s34", function()
            chat("Only 12% of boys who believe they are transgender still believe so when they are older.")
            setclipboard("archive.md/S3s34")
        end)
        Transsexuality:NewButton("MtF transgenders have alternate motives", "https://archive.md/gHxfh", function()
            chat("MRI scans indicate that male-to-female transgenders are either men who 'like' the thought of possessing female organs or gays attracted to straight men.")
            setclipboard("archive.md/gHxfh")
        end)
        Transsexuality:NewButton("53% of mothers of trans kids have BPD", "https://archive.md/xZ8Ie", function()
            chat("53% of mothers of transgender children have Borderline Personality Disorder, compared to only 6% of mothers of normal children.")
            setclipboard("archive.md/xZ8Ie")
        end)
        Transsexuality:NewButton("41% of trans attempt suicide", "https://archive.md/G8AmS", function()
            chat("41% of transgenders have tried and failed to commit svxccide.")
            setclipboard("archive.md/G8AmS")
        end)
        Transsexuality:NewButton("37% of trans youth attempted suicide in past year", "https://archive.md/uJoYU", function()
            chat("37% of transgender youth have attempted svxccide within the last year.")
            setclipboard("archive.md/uJoYU")
        end)
        Transsexuality:NewButton("Only 21% of transgenders pass", "https://archive.md/yHyBg", function()
            chat("Only 21% of trzxns genders can successfully pass as the opposite gender.")
            setclipboard("archive.md/yHyBg")
        end)
        Transsexuality:NewButton("Gay/Trans students 50% as likely to graduate", "https://archive.md/oaHQo", function()
            chat("Gay and transgender students are half as likely to graduate high school as straight students.")
            setclipboard("archive.md/oaHQo")
        end)
        Transsexuality:NewButton("Transgenders more likely to be autistic", "https://archive.md/oN1GF", function()
            chat("Trzxns genders are more likely to have autism than the general population.")
            setclipboard("archive.md/oN1GF")
        end)
        Transsexuality:NewButton("80% of 'trans' kids abandon the idea", "https://archive.md/ysTrZ", function()
            chat("Close to 80% of children who feel transgender will abandon their confusion as they grow older.")
            setclipboard("archive.md/ysTrZ")
        end)
        Transsexuality:NewButton("Many transgenders pick HRT over HIV meds", "https://archive.md/bKBYx", function()
            chat("Many trzxns genders choose to take hormone treatments over HZXV mzxdication.")
            setclipboard("archive.md/bKBYx")
        end)

    local SoyMen = LGBT:NewSection("Soy Men")
        SoyMen:NewButton("Liberal men are more willing to date nonwhites", "https://archive.md/9qJcJ", function()
            chat("Liberal men are more willing to date non-Whites.")
            setclipboard("archive.md/9qJcJ")
        end)
        SoyMen:NewButton("Weaker men are more liberal", "https://archive.md/hIV9l", function()
            chat("Weaker men are more liberal than stronger men.")
            setclipboard("archive.md/hIV9l")
        end)
        SoyMen:NewButton("Weaker men support redistribution of wealth", "https://archive.md/3EMZL", function()
            chat("Weaker men are genetically more likely to support redistribution.")
            setclipboard("archive.md/3EMZL")
        end)
        SoyMen:NewButton("Muscle strength decreases depression", "pubmed.ncbi.nlm.nih.gov/26169439/", function()
            chat("Muscular strength increases self-esteem and decreases depression, szxscide, and hopelessness.")
            setclipboard("pubmed.ncbi.nlm.nih.gov/26169439/")
        end)

    local WomenSexRoles = LGBT:NewSection("Women + Sex Roles")
        WomenSexRoles:NewButton("Women take less competitive jobs", "https://ftp.iza.org/dp8563.pdf", function()
            chat("Womzxn are less likely to be emplzxyed in highly competitive jobs.")
            setclipboard("ftp.iza.org/dp8563.pdf")
        end)
        WomenSexRoles:NewButton("Better societies have more gender roles", "https://archive.md/yZnnd", function()
            chat("More advanced societies have more differentiated gender roles.")
            setclipboard("archive.md/yZnnd")
        end)
        WomenSexRoles:NewButton("Women w/ >20 partners have 80% divorce chance", "https://archive.md/jz0bB", function()
            chat("Women w/ a body count over 20 have an 80% chance of divorce.")
            setclipboard("archive.md/jz0bB")
        end)
        WomenSexRoles:NewButton("Gender stereotypes correctly predict academics", "https://archive.md/1o7M9", function()
            chat("Gender stereotypes are correct predictors of math and reading ability.")
            setclipboard("archive.md/1o7M9")
        end)
        WomenSexRoles:NewButton("College majors w/ more women have lower IQ", "https://archive.md/HgJHA", function()
            chat("College students who major in fields with a greater proportion of women have lower average IQ.")
            setclipboard("archive.md/HgJHA")
        end)
        WomenSexRoles:NewButton("Less attractive women want careers", "https://archive.md/naxd5", function()
            chat("Less attractive women are more likely to want careers.")
            setclipboard("archive.md/naxd5")
        end)
        WomenSexRoles:NewButton("Gender differences are by choice (wage gap)", "https://archive.md/nBJ54", function()
            chat("Gender differences in the West are the result of free choices made by innately different men and women.")
            setclipboard("archive.md/nBJ54")
        end)
        WomenSexRoles:NewButton("Stay at home wives are happier", "https://archive.md/3oq80", function()
            chat("Stay-at-home wzyves are more content than working wzyves.")
            setclipboard("archive.md/3oq80")
        end)
        WomenSexRoles:NewButton("Feminist women are less happy", "https://archive.md/3oq80", function()
            chat("Progressive/feminist women are less happy than their peers.")
            setclipboard("archive.md/3oq80")
        end)

    local Attractiveness = LGBT:NewSection("Attractiveness")
        Attractiveness:NewButton("Women with fat ass have smarter kids", "https://archive.md/LNg0t", function()
            chat("Women with low waist-to-hip ratios produce smarter children.")
            setclipboard("archive.md/LNg0t")
        end)
        Attractiveness:NewButton("Attractive/Successful women are straight", "https://archive.md/ncBBO", function()
            chat("Attractive and successful women are more likely to be straight.")
            setclipboard("archive.md/ncBBO")
        end)
        Attractiveness:NewButton("Attractiveness is 80% objective", "https://archive.md/zxYyM", function()
            chat("Attractiveness is about 80% shared and 20% in the eye of the beholder.")
            setclipboard("archive.md/zxYyM")
        end)
        Attractiveness:NewButton("Biological definition of beauty exists", "https://archive.md/CTIyw", function()
            chat("There is a biological basis in a portion of the brain for objective beauty.")
            setclipboard("archive.md/CTIyw")
        end)


local Islam = Window:NewTab("Islam")
    local GeneralIslam = Islam:NewSection("General Facts")
        GeneralIslam:NewButton("36% of Muslims support 9/11", "https://archive.is/E6RlD", function()
            chat("36% of Islamists believe 9/11 was partially or wholly justified!")
            setclipboard("archive.is/E6RlD")
        end)
        GeneralIslam:NewButton("Half of Muslims are inbred", "https://archive.is/SFnej", function()
            chat("HALF of all Islamists are 'inbread.'")
            setclipboard("archive.is/SFnej")
        end)
        GeneralIslam:NewButton("Rape of infidels = Islamic law", "https://archive.is/0EgTk", function()
            chat("Raezxpe of infidel women is part of Islamic law and Islamic tradition.")
            setclipboard("archive.is/0EgTk")
        end)
        GeneralIslam:NewButton("300 million Muslims support ISIS", "https://archive.is/tsGes", function()
            chat("As many as 300 million Islamists may support 'eyes is.'")
            setclipboard("archive.is/tsGes")
        end)
        GeneralIslam:NewButton("11.5% of Arabs support ISIS", "https://archive.is/9kE7n", function()
            chat("'Eyes is' = supported by 11.5% of Arabs, or 42 million people.")
            setclipboard("archive.is/9kE7n")
        end)
        GeneralIslam:NewButton("1/8 of Muslims favor Al Qaeda", "https://archive.is/eyCAB", function()
            chat("One in eight Islamists worldwide has a favorable view of 'Al Kayda.'")
            setclipboard("archive.is/eyCAB")
        end)
        GeneralIslam:NewButton("1/4 of Palestinians support attacks on US", "https://archive.is/Zqn9U", function()
            chat("One in four Palestinians approves of attacks on US civilians on US soil.")
            setclipboard("archive.is/Zqn9U")
        end)
        GeneralIslam:NewButton("Muslim nations <1/10 scientific research avg", "https://archive.is/s4oZ", function()
            chat("The average Islamist nation produces less than 1/10 as much scientific research as a non-Islamist nation.")
            setclipboard("archive.is/s4oZ")
        end)
        GeneralIslam:NewKeybind("Toggle UI", "Right Shift to toggle UI", Enum.KeyCode.RightShift, function()
            Library:ToggleUI()
        end)

    local NorthAmericaIslam = Islam:NewSection("North American Islam")
        NorthAmericaIslam:NewButton("62% of Canadian Muslims want Sharia", "https://archive.is/gYa65", function()
            chat("62% of Canadian Islamists want Sharia law!")
            setclipboard("archive.is/gYa65")
        end)
        NorthAmericaIslam:NewButton("11% of US Muslims support worldwide Sharia law", "https://archive.is/xMxgu", function()
            chat("11% of Islamists in the USA believe that Sharia law must be imposed worldwide through 'Jihawd.'")
            setclipboard("archive.is/xMxgu")
        end)
        NorthAmericaIslam:NewButton("1/4 US Muslim youth justify terrorism", "https://archive.is/n04zA", function()
            chat("One in four young Islamists in the USA believes that 'terrxorism' is justified.")
            setclipboard("archive.is/n04zA")
        end)
        NorthAmericaIslam:NewButton("1/4 USA Muslims support Jihad against Americans", "https://archive.is/xMxgu", function()
            chat("One in four American Islamists believe that violence against Americans is acceptable as part of Jihawd.")
            setclipboard("archive.is/xMxgu")
        end)
        NorthAmericaIslam:NewButton("Resettling refugees 12x more expensive", "https://archive.is/nj5Ia", function()
            chat("Resettling 'ref ugeez' in the West is 12x more expensive than caring for them in their home countries.")
            setclipboard("archive.is/nj5Ia")
        end)
        NorthAmericaIslam:NewButton("80% of Somali-USA immigration was illegal", "https://archive.is/Pdst8", function()
            chat("In 2008, 80% of Somali immigration to the United States was fraudulent.")
            setclipboard("archive.is/Pdst8")
        end)
        NorthAmericaIslam:NewButton("Immigration increases inbreeding", "https://archive.is/zDwbJ", function()
            chat("Immigration to Europe and North America from Islamic countries has raised the amount of 'in breading' in our countries.")
            setclipboard("archive.is/zDwbJ")
        end)
        NorthAmericaIslam:NewButton("90% of Middle East immigrants pay no tax", "https://archive.is/nj5Ia", function()
            chat("NINETY PERCENT of Middle Eastern immigrants to the USA pay NO income tax and receive money from the government.")
            setclipboard("archive.is/nj5Ia")
        end)

    local EuropeanIslam = Islam:NewSection("European Islam")
        EuropeanIslam:NewButton("65% of EU Muslims prioritize Sharia over the law", "https://archive.is/B9GCV", function()
            chat("65% of European Islamists believe that Sharia law is more important than the law of their country.")
            setclipboard("archive.is/B9GCV")
        end)
        EuropeanIslam:NewButton("Islam in home country predicts crime", "https://archive.md/a74C4", function()
            chat("One of best predictors of crime among 'mi grants' to the EU is the prevalence of 'Izslamism' in their home country.")
            setclipboard("archive.md/a74C4")
        end)
        EuropeanIslam:NewButton("75% of migrants to EU are military-age males", "https://archive.is/tsGes", function()
            chat("75 to 80 percent of 'mi grants' entering Europe are military 'a ge' males in generally good health.")
            setclipboard("archive.is/tsGes")
        end)
        EuropeanIslam:NewButton(">20% of Muslim migrants to EU have ISIS ties", "https://archive.is/tsGes", function()
            chat("More than 20% of Islamist 'mi grants' entering Europe may have ties to 'eyes is' affiliated groups!")
            setclipboard("archive.is/tsGes")
        end)
        EuropeanIslam:NewButton("EU migrants 2x as likely to drop out", "https://archive.is/Pbao2", function()
            chat("'Mi grants' to Europe are twice as likely to drop out of school and be unemployed as Whi te Europ eans.")
            setclipboard("archive.is/Pbao2")
        end)


local Furries = Window:NewTab("Furries")
    local Zoophilia = Furries:NewSection("Sexuality + Zoophilia")
        Zoophilia:NewButton("78.5% of furries not straight", "https://archive.md/ICtsQ", function()
            chat("78.5% of furries said they were not completely straight.")
            setclipboard("archive.md/ICtsQ")
        end)
        Zoophilia:NewButton("14.9% of furries are zoophiles", "https://archive.md/44kck", function()
            chat("From a combined sample size of over 35 thousand furries, 14.9% said they were zoophzxles.")
            setclipboard("archive.md/44kck")
        end)
    local OtherFurries = Furries:NewSection("Other")
        OtherFurries:NewButton("Only 78% identify as human", "https://archive.fo/4nWc5", function()
            chat("Only 78% of furries strongly 'identify' as human.")
            setclipboard("archive.fo/4nWc5")
        end)
        OtherFurries:NewButton("61.7% of furries were bullied", "https://archive.md/N9M65", function()
            chat("61.7% of furries reported being bullied from when they were 11 to adulthood.")
            setclipboard("archive.md/N9M65")
        end)
        OtherFurries:NewButton("15% of furries have autism", "https://archive.md/xsBXa", function()
            chat("15% of furries have autism spectrum disorder.")
            setclipboard("archive.md/xsBXa")
        end)
        OtherFurries:NewButton("80% are male but 45% identify as such", "https://archive.md/JiehE", function()
            chat("80% of furries are biologically male, but only 45% identify with the male gender.")
            setclipboard("archive.md/JiehE")
        end)
        OtherFurries:NewButton("33% of furries come from divorce", "https://archive.md/JiehE", function()
            chat("33.6% of furries reported that their parents had been divorced.")
            setclipboard("archive.md/JiehE")
        end)


local Diversity = Window:NewTab("Diversity+Ethnocentrism")
    local DiversitySection = Diversity:NewSection("Diversity")
        DiversitySection:NewButton("Diverse neighborhoods have less social cohesion", "https://archive.md/HEKKi", function()
            chat("More diverse neighborhoods have lower social cohesion.")
            setclipboard("archive.md/HEKKi")
        end)
        DiversitySection:NewButton("Diversity reduces quality of community", "https://archive.md/8i1Is", function()
            chat("Diversity reduces voter registration, political efficacy, charity, and number of friendships.")
            setclipboard("archive.md/8i1Is")
        end)
        DiversitySection:NewButton("Ethnic diversity reduces happiness", "https://archive.md/8i1Is", function()
            chat("Ethnic diversity reduces happiness and quality of life.")
            setclipboard("archive.md/8i1Is")
        end)
        DiversitySection:NewButton("Diversity reduces trust", "https://archive.md/6lKZB", function()
            chat("Diversity reduces trust, civic participation, and civic health.")
            setclipboard("archive.md/6lKZB")
        end)
        DiversitySection:NewButton("Diversity hurts the dominant ethnic group", "https://archive.md/783wK", function()
            chat("Diversity primarily hurts the dominant ethnic group.")
            setclipboard("archive.md/783wK")
        end)
        DiversitySection:NewButton("Diversity within 80m reduces trust", "https://archive.md/mrTGs", function()
            chat("Ethnic diversity within 80 meters of a person reduces social trust.")
            setclipboard("archive.md/mrTGs")
        end)
        DiversitySection:NewButton("Homogeneity benefits society", "https://archive.md/pcw5f", function()
            chat("Homogeneous polities have less crime, less civil war, and more altruism.")
            setclipboard("archive.md/pcw5f")
        end)
        DiversitySection:NewButton("Borders reduce violence", "https://archive.md/TSfPM", function()
            chat("Borders, not multiculturalism, reduce intergroup violence. ")
            setclipboard("archive.md/TSfPM")
        end)
        DiversitySection:NewButton("Blacks trust neighbors less", "https://archive.md/8i1Is", function()
            chat("Black people trust their neighbors less than White people do.")
                setclipboard("archive.md/8i1Is")
        end)
        DiversitySection:NewButton("Spanish speakers trust neighbors less", "https://archive.md/8i1Is", function()
            chat("Spanish speakers trust their neighbors less than English speakers do.")
                setclipboard("archive.md/8i1Is")
        end)
        DiversitySection:NewButton("Genetic diversity causes conflict", "https://archive.md/Gjqo9", function()
            chat("Genetic diversity causes societal conflict.")
            setclipboard("archive.md/Gjqo9")
        end)

    local Ethnocentrism = Diversity:NewSection("Ethnocentrism")
        Ethnocentrism:NewButton("Ethnocentrism is rational", "https://archive.md/G5p7h", function()
            chat("Ethnocentrism is rational, biological, and genetic in origin.")
            setclipboard("archive.md/G5p7h")
        end)
        Ethnocentrism:NewButton("Babies demonstrate ethnocentrism", "https://archive.md/kjHEW", function()
            chat("Babies demonstrate ethnocentrism before exposure to non-Whites.")
            setclipboard("archive.md/kjHEW")
        end)
        Ethnocentrism:NewButton("Ethnocentrism is biological", "https://archive.md/VooCZ", function()
            chat("Ethnocentrism is biological in origin and a superior evolutionary strategy to altruism.")
            setclipboard("archive.md/VooCZ")
        end)
        Ethnocentrism:NewButton("People subconsciously prefer genetically alike people", "https://archive.md/cZXzC", function()
            chat("People subconsciously prefer those who are genetically similar to them for biologically rational reasons.")
            setclipboard("archive.md/cZXzC")
        end)


local Intelligence = Window:NewTab("Intelligence")
    local IQSection = Intelligence:NewSection("Intelligence")
        IQSection:NewButton("Intelligence is heritable", "https://archive.md/XnPB1", function()
            chat("Human intelligence is highly heritable.")
            setclipboard("archive.md/XnPB1")
        end)
        IQSection:NewButton("IQ tests not biased", "https://archive.md/j85e7", function()
            chat("The scientific consensus is that IQ tests are not racially biased.")
            setclipboard("archive.md/j85e7")
        end)
        IQSection:NewButton("Poor whites as smart as rich blacks", "https://archive.md/PKrYw", function()
            chat("Very poor Whites are about as intelligent as very wealthy Blacks.")
            setclipboard("archive.md/PKrYw")
        end)
        IQSection:NewButton("IQ experts hold hereditarian views", "https://archive.md/vm4H7", function()
            chat("Privately, intelligence experts hold more hereditarian views than they express in public.")
            setclipboard("archive.md/vm4H7")
        end)
        IQSection:NewButton("Black children have similar IQ despite household", "https://archive.md/oNKYp", function()
            chat("Black children raised in White households have similar IQ scores to Black children in Black households.")
            setclipboard("archive.md/oNKYp")
        end)
        IQSection:NewButton("Average African IQ is 75", "https://archive.md/YRHuH", function()
            chat("The average African IQ is estimated at 75.")
            setclipboard("archive.md/YRHuH")
        end)
        IQSection:NewButton("Genes for large brains not in Africa", "https://archive.md/jrgAY", function()
            chat("Genes for large brains, linked to high IQ, are common everywhere except Africa.")
            setclipboard("archive.md/jrgAY")
        end)
        IQSection:NewButton("IQ scores predict success", "https://archive.md/bnJzq", function()
            chat("IQ scores are the best predictor of success in Western society.")
            setclipboard("archive.md/bnJzq")
        end)
        IQSection:NewButton("Average Hispanic IQ is 90", "https://archive.md/NVivo", function()
            chat("The average Hispanic IQ is 90.")
            setclipboard("archive.md/NVivo")
        end)
        IQSection:NewButton("Sub-Saharan African IQ is 70", "https://archive.md/NVivo", function()
            chat("The average IQ in Sub-Saharan Africa is 70.")
            setclipboard("archive.md/NVivo")
        end)
        IQSection:NewButton("Southeast Asian IQ is 87", "https://archive.md/NVivo", function()
            chat("The average IQ in southeast Asia is 87.")
            setclipboard("archive.md/NVivo")
        end)
        IQSection:NewButton("Least intelligent countries are in Africa", "https://www.cambridge.org/core/journals/twin-research-and-human-genetics/article/limits-of-democratization-climate-intelligence-and-resource-distributiontatu-vanhanen-2009-atlanta-ga-washington-summit-publishers-362-pp-us2195-isbn-9781593680312/0187BD8652E580D02E11594AAB559FC3", function()
            chat("The world's thirty least intelligent countries (except for Haiti) are all in sub-Saharan Africa.")
            setclipboard("cambridge.org")
        end)
        IQSection:NewButton("Skin color predicts IQ", "https://archive.md/26JQR", function()
            chat("Skin color is the best biological predictor of IQ. ")
            setclipboard("archive.md/26JQR")
        end)


local JewTab = Window:NewTab("Jews")
    local JewSection = JewTab:NewSection("Jews")
        JewSection:NewButton("Jews changed scientific consensus on race", "https://archive.md/44r9B", function()
            chat("dJhews, Blacks, and women were instrumental in turning the scientific consensus against the validity of race.")
            setclipboard("archive.md/44r9B")
        end)
        JewSection:NewButton("Jews 100x more likely to be billionaires", "https://archive.md/yHVOh", function()
            chat("Per capita, djhews are a little over 100 times more likely to become billionaires than the rest of the human race.")
            setclipboard("archive.md/yHVOh")
        end)
        JewSection:NewButton("0.2% of population; 11% of billionaires", "https://archive.md/yHVOh", function()
            chat("djhews are 0.2% of the global population and 11% of billionaires worldwide.")
            setclipboard("archive.md/yHVOh")
        end)
        JewSection:NewButton("2% of USA; 24% of USA billionaires", "https://archive.md/yHVOh", function()
            chat("djhews are 2% of the USA population and 24% of USA billionaires.")
            setclipboard("archive.md/yHVOh")
        end)
        JewSection:NewButton("ACLU+ADL are Jewish organizations", "Google it 5head", function()
            chat("The ACLU and the ADL are djhewish organizations.")
            setclipboard("")
        end)
        JewSection:NewButton("ADL head declares antizionism = antisemitism", "https://www.algemeiner.com", function()
            chat("The head of the ADL has declared that 'antizi onism is Antisemitism.'")
            setclipboard("algemeiner.com")
        end)
        JewSection:NewButton("Hollywood was founded by Jews", "The book An Empire of Their Own", function()
            chat("Hollywood was founded almost entirely by djhews and the media business is completely dominated by (((them))).")
            setclipboard("the book 'An Empire of Their Own'")
        end)
        JewSection:NewButton("List of media controlled by Jews", "Google it", function()
            chat("The president + CEO of CNN, CEO + chairman of The New York Times, CEO of Cxzomcast, executive chairman + CEO of Disney, and CEO of Buzzfeed are all dJhewish. This is not a complete list.")
            setclipboard("")
        end)
        JewSection:NewButton("Jews started WWII", "Russia from the American Embassy by David Francis", function()
            chat("djhews played a central role in orchestrating the start of WWII.")
            setclipboard("The book 'Russia from the American Embassy' by David Francis")
        end)

local BibleTab = Window:NewTab("Bible Verses")
    local TransBibleSection = BibleTab:NewSection("On (trans)gender")
        TransBibleSection:NewButton("Men cannot wear women clothes + vice versa", "Deuteronomy 22:5 ESV", function()
            chat("Deuteronomy 22:5 - A woman shall not wear a man's garment, nor shall a man put on a woman's cloak, for whoever does these things is an abomination to the Lord your God.")
        end)
        TransBibleSection:NewButton("Post-MtF surgery cannot attend church", "Deuteronomy 23:1 ESV", function()
            chat("Deuteronomy 23:1 - No one whose tzxsticles are crushed or whose male organ is cut off shall enter the assembly of the Lord.")
        end)
        TransBibleSection:NewButton("There are only 2 genders", "Genesis 1:27 ESV", function()
            chat("Genesis 1:27 - So God created man in his own image, in the image of God he created him; male and female he created them.")
        end)
        TransBibleSection:NewButton("There are only 2 genders (different verse)", "Genesis 5:2 ESV", function()
            chat("Genesis 5:2 - Male and female he created them, and he blessed them and named them Man when they were created.")
        end)
    local GayBibleSection = BibleTab:NewSection("On Homosexuality")
        GayBibleSection:NewButton("Gay sex is an abomination", "Leviticus 18:22 ESV", function()
            chat("Leviticus 18:22 - You shall not lie with a male as with a woman; it is an abomination.")
        end)
        GayBibleSection:NewButton("Gay sex shall be punished by death", "Leviticus 20:13 ESV", function()
            chat("Leviticus 20:13 - If a man lies with a male as with a woman, both of them have committed an abomination; they shall surely be put to death; their blood is upon them.")
        end)
        GayBibleSection:NewButton("Gays don't go to heaven (3 msgs)", "1 Corinthians 6:9-10 ESV", function()
            chat("1 Corinthians 6:9-10 -  Or do you not know that the unrighteous will not inherit the kingdom of God?")
            wait(0.1)
            chat("Do not be deceived: neither the seskually immoral, nor idolaters, nor adzxlterers, nor men who practice homosexuality,")
            wait(0.1)
            chat("nor thieves, nor the greedy, nor drzxnkards, nor revilers, nor swindlers will inherit the kingdom of God.")
        end)
        GayBibleSection:NewButton("Gays suffer eternal fire (2 msgs)", "Jude 1:7 ESV", function()
            chat("Jude 1:7 -")
            wait(0.05)
            chat("Just as Sodzom and Gomozrrah and the surrounding cities, which likewise indulged in seskual immorality and pursued unnatural desire, serve as an example by undergoing a punishment of eternal fire.")
        end)
    local BibleParaphraseSection = BibleTab:NewSection("Paraphrasings and Analysis")
        BibleParaphraseSection:NewButton("The new testament also forbids homosexuality", "1 Cor 6:9-10; 1 Timothy 1:9-10; Jude 1:7; Romans 1:26-27", function()
            chat("The New Testament explicitly forbids being gay in several places.")
        end)
    local WomanBibleSection = BibleTab:NewSection("On Women")
        WomanBibleSection:NewButton("Women stay silent in church (2 msgs)", "1 Corinthians 14:34-35 ESV", function()
            chat("Corinthians 14:34-35 - The women should keep silent in the churches. For they are not permitted to speak, but should be in submission, as the Law also says.")
            chat("If there is anything they desire to learn, let them ask their hzxsbands at home. For it is shameful for a woman to speak in church. ")
        end)
        WomanBibleSection:NewButton("Women should be quiet (2 msgs)", "1 Timothy 2:11-14 ESV", function()
            chat("1 Timothy 2:11-14 - Let a woman learn quietly with all submissiveness. I do not permit a woman to teach or to exercise authority over a man; rather, she is to remain quiet.")
            chat("For Adam was formed first, then Eve; and Adam was not deceived, but the woman was deceived and became a transgressor.")
        end)

local ConspiraciesTab = Window:NewTab("Conspiracies")
    local NineElevenSection = ConspiraciesTab:NewSection("9/11")
        NineElevenSection:NewButton("$2.3 Trillion missing", "$2.3 trillion went missing the day before 9/11", function()
            chat("The day before 9/11 happened, the Pentagon announced that $2.3 trillion had gone missing.")
            setclipboard("archive.ph/MJ1Ae#")
        end)
        NineElevenSection:NewButton("WTC was insured 6 weeks before", "Larry Silverstein insured the towers just weeks before", function()
            chat("Lxarry Sixlverstein, the owner of the World Trade Center, had the towers insured in a record-breakingly huge policy just six weeks before the attacks.")
            setclipboard("archive.ph/V0NL2")
        end)
        NineElevenSection:NewButton("Tower 7 fell", "3 towers fell for only 2 planes", function()
            chat("Only two planes hit towers in New York, but three towers fell down. The third tower can be seen falling perfectly downwards as is consistent with controlled demolition. Look up 'Tower 7 collapse.'")
            setclipboard("Look up 'Tower 7 collapse' on YouTube. They take down more videos every year.")
        end)
        NineElevenSection:NewButton("Patriot Act infringements afterwards", "Following 9/11, the patriot act was passed and took away rights", function()
            chat("Immediately after 9/11, Congress and Bxush approved the PATRIOT Act to 'fight txzerrorism,' parts of which have since been found unconstitutional for the rights they take away from citizens.")
            setclipboard('Google the "Patriot Act."')
        end)
        NineElevenSection:NewButton("Bush used patriotism to start Iraq War", "George Bush harnessed increased patriotism to gain approval for a 'war on terror'", function()
            chat("Following 9/11, Gexzorge Bxush used increased feelings of patriotism to gain public support for a 'war on terror,' which really just served to conquer oil-rich territories for money.")
            setclipboard('')
        end)
        NineElevenSection:NewButton("Firefighters testified about explosions", "Firefighters said they saw and heard explosions before towers came down", function()
            chat("There are several video testimonies of firefighters describing the explosions they heard from Tower 7 immediately before its collapse.")
            setclipboard("Look up 'firefighter testimony Tower 7.'")
        end)

local MiscTab = Window:NewTab("Miscellaneous")
    local ScriptSection = MiscTab:NewSection("Other Scripts")
        ScriptSection:NewButton("Rate my Avatar 1 star all", "Rates everybody 1 star on Rate My Avatar", function()
            local function a(b)game.StarterGui:SetCore("SendNotification",{Title="PLOOBWARE",Text="Rated "..b.." 1/5 stars",Icon="",Duration=5})end;for c,d in pairs(game:GetService("Players"):GetDescendants())do if d:IsA("Player")then print(d.Name)local e=game:GetService("Players")[d.Name]local f=1;game:GetService("ReplicatedStorage").PostRating:FireServer(e,f)a(d.Name)end end
        end)
        ScriptSection:NewButton("LGBT Hangout 2 Seizure", "Changes your booth colors extremely quickly", function()
            local event = game.ReplicatedStorage.GoBestie
            local function set_sign_colors(sign_c,text_c,shop_c)
                event:FireServer("Sign",sign_c)
                event:FireServer("Text",text_c)
                event:FireServer("Shop",shop_c)
            end
            local function rand_color3_values()
                return math.random(),math.random(),math.random()
            end
            game:GetService('RunService').RenderStepped:Connect(function()
            set_sign_colors(Color3.new(rand_color3_values()),Color3.new(rand_color3_values()),Color3.new(rand_color3_values()))
            end)
        end)
        ScriptSection:NewButton("R6 Swastika", "Makes your body into a swastika; breaks if you touch things", function()
            plr = game:GetService("Players").LocalPlayer
            rs = game.RunService.RenderStepped
            rootpart = plr.Character:WaitForChild("HumanoidRootPart",5)

            function cpos(p,a,b,c,x,y,z)
                local bf = Instance.new("BodyForce")
                bf.force = Vector3.new(0, 196.2, 0) * p:GetMass()
                bf.Parent = p
                rs:Connect(function()
                    p.CFrame = rootpart.CFrame * CFrame.new(a,b,c) * CFrame.Angles(x,y,z)
                end)
                p:BreakJoints()
            end
            cpos(plr.Character["Left Arm"],-1,1.5,0,0,0,math.rad(-90))
            cpos(plr.Character["Right Arm"],1.5,1,0,0,0,math.rad(180))
            cpos(plr.Character["Left Leg"],-1.5,-1,0,0,0,math.rad(0))
            cpos(plr.Character["Right Leg"],1,-1.5,0,0,0,math.rad(90))
        end)
        ScriptSection:NewButton("ANTICHATBAN", "Does not upload chat messages to roblox's website", function()
            loadstring(game:HttpGet("https://api.upload.systems/pastes/jbU1gHIriNgT/raw"))()
        end)
